// Auto-generated by extract.py
const PRODUCTS = {
  "toilet": [
    {
      "id": "TU-1",
      "model": "2001",
      "name": "分体马桶地排s",
      "spec": "250mm",
      "type": "马桶",
      "price": 490,
      "image": "images/toilet/toilet_TU-1.png"
    },
    {
      "id": "TU-2",
      "model": "2002",
      "name": "澳洲分体马桶 地排S接头/墙排p接头",
      "spec": "",
      "type": "马桶",
      "price": 620,
      "image": "images/toilet/toilet_TU-2.png"
    },
    {
      "id": "TU-3",
      "model": "2003",
      "name": "分体马桶地排S",
      "spec": "250mm",
      "type": "马桶",
      "price": 420,
      "image": "images/toilet/toilet_TU-3.png"
    },
    {
      "id": "TU-4",
      "model": "2004",
      "name": "分体马桶地排S",
      "spec": "",
      "type": "马桶",
      "price": 430,
      "image": "images/toilet/toilet_TU-4.jpeg"
    },
    {
      "id": "TU-5",
      "model": "2005",
      "name": "分体马桶地排S",
      "spec": "",
      "type": "马桶",
      "price": 460,
      "image": "images/toilet/toilet_TU-5.jpeg"
    },
    {
      "id": "TU-6",
      "model": "2006",
      "name": "分体马桶横排S/地排P",
      "spec": "250mm",
      "type": "马桶",
      "price": 510,
      "image": "images/toilet/toilet_TU-6.png"
    },
    {
      "id": "TU-7",
      "model": "2007",
      "name": "分体马桶地排s/墙排p",
      "spec": "250mm",
      "type": "马桶",
      "price": 510,
      "image": "images/toilet/toilet_TU-7.png"
    },
    {
      "id": "TU-8",
      "model": "2008",
      "name": "澳洲分体马桶地排s/墙排p",
      "spec": "",
      "type": "马桶",
      "price": 680,
      "image": "images/toilet/toilet_TU-8.png"
    },
    {
      "id": "TU-9",
      "model": "2009",
      "name": "澳洲分体马桶地排S/墙排P",
      "spec": "",
      "type": "马桶",
      "price": 680,
      "image": "images/toilet/toilet_TU-9.png"
    },
    {
      "id": "TU-10",
      "model": "2010",
      "name": "澳洲分体马桶地排S/墙排P",
      "spec": "",
      "type": "马桶",
      "price": 680,
      "image": "images/toilet/toilet_TU-10.jpeg"
    },
    {
      "id": "TU-11",
      "model": "2028",
      "name": "分体马桶（地排s、墙排P)",
      "spec": "",
      "type": "马桶",
      "price": 0
    },
    {
      "id": "TU-12",
      "model": "2011",
      "name": "分体马桶地排s/墙排p",
      "spec": "250mm",
      "type": "马桶",
      "price": 0
    },
    {
      "id": "TU-13",
      "model": "2025",
      "name": "分体马桶地排s/墙排P",
      "spec": "250mm",
      "type": "马桶",
      "price": 0
    },
    {
      "id": "TU-14",
      "model": "4001",
      "name": "立柱盆",
      "spec": "",
      "type": "立柱盆",
      "price": 240,
      "image": "images/toilet/toilet_TU-14.jpeg"
    },
    {
      "id": "TU-15",
      "model": "4002",
      "name": "立柱盆",
      "spec": "",
      "type": "立柱盆",
      "price": 270,
      "image": "images/toilet/toilet_TU-15.jpeg"
    },
    {
      "id": "TU-4005",
      "model": "4005",
      "name": "立柱盆",
      "spec": "",
      "type": "立柱盆",
      "price": 240,
      "image": "images/toilet/toilet_TU-4005.jpeg"
    },
    {
      "id": "TU-4006",
      "model": "4006",
      "name": "立柱盆",
      "spec": "",
      "type": "立柱盆",
      "price": 240,
      "image": "images/toilet/toilet_TU-4006.jpeg"
    },
    {
      "id": "TU-16",
      "model": "4007",
      "name": "立柱盆",
      "spec": "",
      "type": "立柱盆",
      "price": 240,
      "image": "images/toilet/toilet_TU-16.png"
    },
    {
      "id": "TU-17",
      "model": "4008",
      "name": "立柱盆",
      "spec": "",
      "type": "立柱盆",
      "price": 240,
      "image": "images/toilet/toilet_TU-17.png"
    },
    {
      "id": "TU-4009",
      "model": "4009",
      "name": "立柱盆",
      "spec": "",
      "type": "立柱盆",
      "price": 240,
      "image": "images/toilet/toilet_TU-4009.jpeg"
    },
    {
      "id": "TU-4010",
      "model": "4010",
      "name": "立柱盆",
      "spec": "",
      "type": "立柱盆",
      "price": 240,
      "image": "images/toilet/toilet_TU-4010.jpeg"
    },
    {
      "id": "TU-4011",
      "model": "4011",
      "name": "立柱盆",
      "spec": "",
      "type": "立柱盆",
      "price": 240,
      "image": "images/toilet/toilet_TU-4011.jpeg"
    },
    {
      "id": "TU-4003",
      "model": "4003",
      "name": "立柱盆",
      "spec": "",
      "type": "立柱盆",
      "price": 240
    },
    {
      "id": "TU-4004",
      "model": "4004",
      "name": "立柱盆",
      "spec": "",
      "type": "立柱盆",
      "price": 240
    },
    {
      "id": "TU-18",
      "model": "C003",
      "name": "蹲便器",
      "spec": "",
      "type": "马桶",
      "price": 160,
      "image": "images/toilet/toilet_TU-18.png"
    }
  ],
  "faucet": [
    {
      "id": "HJ-5001",
      "code": "HJ-5001",
      "name": "不锈钢阀体，陶瓷阀芯，ABS把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS把手，冷热水",
      "type": "面盆龙头",
      "price": 135,
      "image": "images/faucet/faucet_HJ-5001.png"
    },
    {
      "id": "HJ-5003",
      "code": "HJ-5003",
      "name": "枪灰色，不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "desc": "枪灰色，不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "type": "面盆龙头",
      "price": 125,
      "image": "images/faucet/faucet_HJ-5003.png"
    },
    {
      "id": "HJ-5004",
      "code": "HJ-5004",
      "name": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "type": "面盆龙头",
      "price": 130,
      "image": "images/faucet/faucet_HJ-5004.png"
    },
    {
      "id": "HJ-5005",
      "code": "HJ-5005",
      "name": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "type": "面盆龙头",
      "price": 145,
      "image": "images/faucet/faucet_HJ-5005.png"
    },
    {
      "id": "HJ-5006",
      "code": "HJ-5006",
      "name": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "type": "面盆龙头",
      "price": 100,
      "image": "images/faucet/faucet_HJ-5006.png"
    },
    {
      "id": "HJ-5007",
      "code": "HJ-5007",
      "name": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "type": "面盆龙头",
      "price": 115,
      "image": "images/faucet/faucet_HJ-5007.png"
    },
    {
      "id": "HJ-5008",
      "code": "HJ-5008",
      "name": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "type": "面盆龙头",
      "price": 155,
      "image": "images/faucet/faucet_HJ-5008.png"
    },
    {
      "id": "HJ-5009",
      "code": "HJ-5009",
      "name": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "type": "面盆龙头",
      "price": 135,
      "image": "images/faucet/faucet_HJ-5009.png"
    },
    {
      "id": "HJ-5010",
      "code": "HJ-5010",
      "name": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "type": "面盆龙头",
      "price": 150,
      "image": "images/faucet/faucet_HJ-5010.png"
    },
    {
      "id": "HJ-5011",
      "code": "HJ-5011",
      "name": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "type": "面盆龙头",
      "price": 245,
      "image": "images/faucet/faucet_HJ-5011.png"
    },
    {
      "id": "HJ-5012",
      "code": "HJ-5012",
      "name": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，不锈钢把手，冷热水",
      "type": "面盆龙头",
      "price": 220,
      "image": "images/faucet/faucet_HJ-5012.png"
    },
    {
      "id": "HJ-4001",
      "code": "HJ-4001",
      "name": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 60,
      "image": "images/faucet/faucet_HJ-4001.png"
    },
    {
      "id": "HJ-4002",
      "code": "HJ-4002",
      "name": "合金阀体，陶瓷阀芯，合金把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，合金把手，单冷",
      "type": "面盆龙头",
      "price": 60,
      "image": "images/faucet/faucet_HJ-4002.png"
    },
    {
      "id": "HJ-4003",
      "code": "HJ-4003",
      "name": "合金阀体，陶瓷阀芯，合金把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，合金把手，单冷",
      "type": "面盆龙头",
      "price": 60,
      "image": "images/faucet/faucet_HJ-4003.png"
    },
    {
      "id": "HJ-4005",
      "code": "HJ-4005",
      "name": "合金阀体，陶瓷阀芯，合金把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，合金把手，单冷",
      "type": "面盆龙头",
      "price": 35,
      "image": "images/faucet/faucet_HJ-4005.png"
    },
    {
      "id": "HJ-4006",
      "code": "HJ-4006",
      "name": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 40,
      "image": "images/faucet/faucet_HJ-4006.png"
    },
    {
      "id": "HJ-4007",
      "code": "HJ-4007",
      "name": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 45,
      "image": "images/faucet/faucet_HJ-4007.png"
    },
    {
      "id": "HJ-4008",
      "code": "HJ-4008",
      "name": "合金阀体，陶瓷阀芯，单冷",
      "desc": "合金阀体，陶瓷阀芯，单冷",
      "type": "面盆龙头",
      "price": 80,
      "image": "images/faucet/faucet_HJ-4008.png"
    },
    {
      "id": "HJ-4009",
      "code": "HJ-4009",
      "name": "合金阀体，陶瓷阀芯，单冷",
      "desc": "合金阀体，陶瓷阀芯，单冷",
      "type": "面盆龙头",
      "price": 80,
      "image": "images/faucet/faucet_HJ-4009.png"
    },
    {
      "id": "HJ-4010",
      "code": "HJ-4010",
      "name": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 60,
      "image": "images/faucet/faucet_HJ-4010.png"
    },
    {
      "id": "HJ-4011",
      "code": "HJ-4011",
      "name": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 80,
      "image": "images/faucet/faucet_HJ-4011.png"
    },
    {
      "id": "HJ-6001",
      "code": "HJ-6001",
      "name": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "type": "厨房龙头",
      "price": 125,
      "image": "images/faucet/faucet_HJ-6001.png"
    },
    {
      "id": "HJ-6002",
      "code": "HJ-6002",
      "name": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "type": "厨房龙头",
      "price": 145,
      "image": "images/faucet/faucet_HJ-6002.png"
    },
    {
      "id": "HJ-6003",
      "code": "HJ-6003",
      "name": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "type": "厨房龙头",
      "price": 190,
      "image": "images/faucet/faucet_HJ-6003.png"
    },
    {
      "id": "HJ-6004",
      "code": "HJ-6004",
      "name": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "type": "厨房龙头",
      "price": 220,
      "image": "images/faucet/faucet_HJ-6004.png"
    },
    {
      "id": "HJ-6005",
      "code": "HJ-6005",
      "name": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "type": "厨房龙头",
      "price": 210,
      "image": "images/faucet/faucet_HJ-6005.png"
    },
    {
      "id": "HJ-6006",
      "code": "HJ-6006",
      "name": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "type": "厨房龙头",
      "price": 180,
      "image": "images/faucet/faucet_HJ-6006.png"
    },
    {
      "id": "HJ-6007",
      "code": "HJ-6007",
      "name": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "type": "厨房龙头",
      "price": 190,
      "image": "images/faucet/faucet_HJ-6007.png"
    },
    {
      "id": "HJ-6008",
      "code": "HJ-6008",
      "name": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "desc": "不锈钢阀体，陶瓷阀芯，合金把手，冷热水",
      "type": "厨房龙头",
      "price": 210,
      "image": "images/faucet/faucet_HJ-6008.png"
    },
    {
      "id": "HJ-3001",
      "code": "HJ-3001",
      "name": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 20,
      "image": "images/faucet/faucet_HJ-3001.png"
    },
    {
      "id": "HJ-3002",
      "code": "HJ-3002",
      "name": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 55,
      "image": "images/faucet/faucet_HJ-3002.png"
    },
    {
      "id": "HJ-3003",
      "code": "HJ-3003",
      "name": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 60,
      "image": "images/faucet/faucet_HJ-3003.png"
    },
    {
      "id": "HJ-3004",
      "code": "HJ-3004",
      "name": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 60,
      "image": "images/faucet/faucet_HJ-3004.png"
    },
    {
      "id": "HJ-3005",
      "code": "HJ-3005",
      "name": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 60,
      "image": "images/faucet/faucet_HJ-3005.png"
    },
    {
      "id": "HJ-3006",
      "code": "HJ-3006",
      "name": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 35,
      "image": "images/faucet/faucet_HJ-3006.png"
    },
    {
      "id": "HJ-3007",
      "code": "HJ-3007",
      "name": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 60,
      "image": "images/faucet/faucet_HJ-3007.png"
    },
    {
      "id": "HJ-3008",
      "code": "HJ-3008",
      "name": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 75,
      "image": "images/faucet/faucet_HJ-3008.png"
    },
    {
      "id": "HJ-3009",
      "code": "HJ-3009",
      "name": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 55,
      "image": "images/faucet/faucet_HJ-3009.png"
    },
    {
      "id": "HJ-3010",
      "code": "HJ-3010",
      "name": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 60,
      "image": "images/faucet/faucet_HJ-3010.png"
    },
    {
      "id": "HJ-3011",
      "code": "HJ-3011",
      "name": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 0,
      "image": "images/faucet/faucet_HJ-3011.png"
    },
    {
      "id": "HJ-3012",
      "code": "HJ-3012",
      "name": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 75,
      "image": "images/faucet/faucet_HJ-3012.png"
    },
    {
      "id": "HJ-3013",
      "code": "HJ-3013",
      "name": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "desc": "合金阀体，陶瓷阀芯，ABS把手，单冷",
      "type": "面盆龙头",
      "price": 0,
      "image": "images/faucet/faucet_HJ-3013.png"
    },
    {
      "id": "HJ-1001",
      "code": "HJ-1001",
      "name": "不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "type": "角阀",
      "price": 13,
      "image": "images/faucet/faucet_HJ-1001.png"
    },
    {
      "id": "HJ-1002",
      "code": "HJ-1002",
      "name": "拉丝，不锈钢阀体，陶瓷阀芯，不锈钢手轮，单冷",
      "desc": "拉丝，不锈钢阀体，陶瓷阀芯，不锈钢手轮，单冷",
      "type": "角阀",
      "price": 20,
      "image": "images/faucet/faucet_HJ-1002.png"
    },
    {
      "id": "HJ-1003",
      "code": "HJ-1003",
      "name": "拉丝，不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "desc": "拉丝，不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "type": "角阀",
      "price": 26,
      "image": "images/faucet/faucet_HJ-1003.png"
    },
    {
      "id": "HJ-7001",
      "code": "HJ-7001",
      "name": "不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "type": "角阀",
      "price": 100,
      "image": "images/faucet/faucet_HJ-7001.png"
    },
    {
      "id": "HJ-7002",
      "code": "HJ-7002",
      "name": "不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "type": "角阀",
      "price": 30,
      "image": "images/faucet/faucet_HJ-7002.png"
    },
    {
      "id": "HJ-7003",
      "code": "HJ-7003",
      "name": "不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "type": "角阀",
      "price": 30,
      "image": "images/faucet/faucet_HJ-7003.png"
    },
    {
      "id": "HJ-7004",
      "code": "HJ-7004",
      "name": "不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "desc": "不锈钢阀体，陶瓷阀芯，ABS手轮，单冷",
      "type": "角阀",
      "price": 60,
      "image": "images/faucet/faucet_HJ-7004.png"
    },
    {
      "id": "HJ-5550",
      "code": "HJ-5550",
      "name": "双杆",
      "desc": "双杆",
      "type": "淋浴管",
      "price": 55,
      "image": "images/faucet/faucet_HJ-5550.png"
    },
    {
      "id": "HJ-5551",
      "code": "HJ-5551",
      "name": "单杆",
      "desc": "单杆",
      "type": "淋浴管",
      "price": 45,
      "image": "images/faucet/faucet_HJ-5551.png"
    },
    {
      "id": "HJ-5552",
      "code": "HJ-5552",
      "name": "马桶刷",
      "desc": "马桶刷",
      "type": "马桶刷",
      "price": 35,
      "image": "images/faucet/faucet_HJ-5552.png"
    },
    {
      "id": "HJ-5553",
      "code": "HJ-5553",
      "name": "201不锈钢",
      "desc": "201不锈钢",
      "type": "地漏",
      "price": 35,
      "image": "images/faucet/faucet_HJ-5553.png"
    },
    {
      "id": "HJ-5554",
      "code": "HJ-5554",
      "name": "HJ-5554",
      "desc": "",
      "type": "地漏",
      "price": 0,
      "image": "images/faucet/faucet_HJ-5554.png"
    },
    {
      "id": "HJ-9001",
      "code": "HJ-9001",
      "name": "不锈钢配件ABS排水管",
      "desc": "不锈钢配件ABS排水管",
      "type": "地漏/配件",
      "price": 28,
      "image": "images/faucet/faucet_HJ-9001.png"
    },
    {
      "id": "HJ-9002",
      "code": "HJ-9002",
      "name": "防臭",
      "desc": "防臭",
      "type": "地漏/配件",
      "price": 35,
      "image": "images/faucet/faucet_HJ-9002.png"
    },
    {
      "id": "HJ-9003",
      "code": "HJ-9003",
      "name": "HJ-9003",
      "desc": "",
      "type": "地漏/配件",
      "price": 0,
      "image": "images/faucet/faucet_HJ-9003.png"
    },
    {
      "id": "HJ-7701",
      "code": "HJ-7701",
      "name": "黑色软管，40cm",
      "desc": "黑色软管，40cm",
      "type": "淋浴管",
      "price": 7
    },
    {
      "id": "HJ-7701",
      "code": "HJ-7701",
      "name": "黑色软管，60cm",
      "desc": "黑色软管，60cm",
      "type": "淋浴管",
      "price": 10,
      "image": "images/faucet/faucet_HJ-7701.png"
    },
    {
      "id": "HJ-7701",
      "code": "HJ-7701",
      "name": "黑色软管，80cm",
      "desc": "黑色软管，80cm",
      "type": "淋浴管",
      "price": 12,
      "image": "images/faucet/faucet_HJ-7701.png"
    },
    {
      "id": "HJ-8001",
      "code": "HJ-8001",
      "name": "产品规格：10*10*3.6，201不锈钢，Sigle",
      "desc": "产品规格：10*10*3.6，201不锈钢，Sigle",
      "type": "地漏",
      "price": 35,
      "image": "images/faucet/faucet_HJ-8001.png"
    },
    {
      "id": "HJ-8002",
      "code": "HJ-8002",
      "name": "产品规格：10*10*3.6，201不锈钢，双",
      "desc": "产品规格：10*10*3.6，201不锈钢，双",
      "type": "地漏",
      "price": 35,
      "image": "images/faucet/faucet_HJ-8002.png"
    },
    {
      "id": "HJ-8003",
      "code": "HJ-8003",
      "name": "201不锈钢",
      "desc": "201不锈钢",
      "type": "地漏",
      "price": 35,
      "image": "images/faucet/faucet_HJ-8003.png"
    },
    {
      "id": "HJ-8004",
      "code": "HJ-8004",
      "name": "不锈钢龙头",
      "desc": "不锈钢材质",
      "type": "地漏",
      "price": 25,
      "image": "images/faucet/faucet_HJ-8004.png"
    },
    {
      "id": "HJ-8005",
      "code": "HJ-8005",
      "name": "不锈钢龙头",
      "desc": "不锈钢材质",
      "type": "地漏",
      "price": 50,
      "image": "images/faucet/faucet_HJ-8005.png"
    },
    {
      "id": "HJ-8621",
      "code": "HJ-8621",
      "name": "ABS花洒，不锈钢管",
      "desc": "ABS花洒，不锈钢管",
      "type": "淋浴套装",
      "price": 45,
      "image": "images/faucet/faucet_HJ-8621.png"
    },
    {
      "id": "HJ-8622",
      "code": "HJ-8622",
      "name": "ABS花洒，不锈钢管",
      "desc": "ABS花洒，不锈钢管",
      "type": "淋浴套装",
      "price": 45,
      "image": "images/faucet/faucet_HJ-8622.png"
    },
    {
      "id": "HJ-8623",
      "code": "HJ-8623",
      "name": "淋浴管",
      "desc": "淋浴管",
      "type": "淋浴套装",
      "price": 25,
      "image": "images/faucet/faucet_HJ-8623.png"
    },
    {
      "id": "HJ-8624",
      "code": "HJ-8624",
      "name": "淋浴管",
      "desc": "淋浴管",
      "type": "淋浴套装",
      "price": 25,
      "image": "images/faucet/faucet_HJ-8624.png"
    },
    {
      "id": "HJ-2001",
      "code": "HJ-2001",
      "name": "铜阀体，陶瓷阀芯，合金把手，冷热水",
      "desc": "铜阀体，陶瓷阀芯，合金把手，冷热水",
      "type": "淋浴套装",
      "price": 245,
      "image": "images/faucet/faucet_HJ-2001.png"
    },
    {
      "id": "HJ-2002",
      "code": "HJ-2002",
      "name": "铜阀体，陶瓷阀芯，合金把手，冷热水",
      "desc": "铜阀体，陶瓷阀芯，合金把手，冷热水",
      "type": "淋浴套装",
      "price": 290,
      "image": "images/faucet/faucet_HJ-2002.png"
    },
    {
      "id": "HJ-2002A",
      "code": "HJ-2002A",
      "name": "铜阀体，陶瓷阀芯，合金把手，冷热水",
      "desc": "铜阀体，陶瓷阀芯，合金把手，冷热水",
      "type": "淋浴套装",
      "price": 290,
      "image": "images/faucet/faucet_HJ-2002A.png"
    },
    {
      "id": "HJ-2003",
      "code": "HJ-2003",
      "name": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "desc": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "type": "淋浴套装",
      "price": 320,
      "image": "images/faucet/faucet_HJ-2003.png"
    },
    {
      "id": "HJ-2003A",
      "code": "HJ-2003A",
      "name": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "desc": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "type": "淋浴套装",
      "price": 320,
      "image": "images/faucet/faucet_HJ-2003A.png"
    },
    {
      "id": "HJ-2004",
      "code": "HJ-2004",
      "name": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "desc": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "type": "淋浴套装",
      "price": 350,
      "image": "images/faucet/faucet_HJ-2004.png"
    },
    {
      "id": "HJ-2004A",
      "code": "HJ-2004A",
      "name": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "desc": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "type": "淋浴套装",
      "price": 350,
      "image": "images/faucet/faucet_HJ-2004A.png"
    },
    {
      "id": "HJ-2009",
      "code": "HJ-2009",
      "name": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "desc": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "type": "淋浴套装",
      "price": 650,
      "image": "images/faucet/faucet_HJ-2009.png"
    },
    {
      "id": "HJ-2010",
      "code": "HJ-2010",
      "name": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "desc": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "type": "淋浴套装",
      "price": 500,
      "image": "images/faucet/faucet_HJ-2010.png"
    },
    {
      "id": "HJ-2011",
      "code": "HJ-2011",
      "name": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "desc": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "type": "淋浴套装",
      "price": 550,
      "image": "images/faucet/faucet_HJ-2011.png"
    },
    {
      "id": "HJ-2012",
      "code": "HJ-2012",
      "name": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "desc": "太空铝阀体，陶瓷阀芯，太空铝把手",
      "type": "淋浴套装",
      "price": 500,
      "image": "images/faucet/faucet_HJ-2012.png"
    },
    {
      "id": "HJ-2005",
      "code": "HJ-2005",
      "name": "即热式电热水器",
      "desc": "即热式电热水器",
      "type": "淋浴套装",
      "price": 600,
      "image": "images/faucet/faucet_HJ-2005.png"
    },
    {
      "id": "HJ-2006",
      "code": "HJ-2006",
      "name": "即热式电热水器",
      "desc": "即热式电热水器",
      "type": "淋浴套装",
      "price": 600,
      "image": "images/faucet/faucet_HJ-2006.png"
    }
  ],
  "cabinet": [
    {
      "id": "YC-1",
      "model": "V8-80",
      "name": "V8-80",
      "spec": "",
      "type": "浴室柜",
      "price": 1020
    },
    {
      "id": "YC-2",
      "model": "A50-80",
      "name": "A50-80",
      "spec": "",
      "type": "浴室柜",
      "price": 1020,
      "image": "images/cabinet/cabinet_YC-2.png"
    },
    {
      "id": "YC-3",
      "model": "J2-60-80",
      "name": "J2-60-80",
      "spec": "60：800  80：1020",
      "type": "浴室柜",
      "price": 0,
      "image": "images/cabinet/cabinet_YC-3.png"
    },
    {
      "id": "YC-4",
      "model": "D9-80",
      "name": "D9-80",
      "spec": "",
      "type": "浴室柜",
      "price": 1020,
      "image": "images/cabinet/cabinet_YC-4.png"
    },
    {
      "id": "YC-5",
      "model": "43-华夏古橡",
      "name": "43-华夏古橡",
      "spec": "",
      "type": "浴室柜",
      "price": 480,
      "image": "images/cabinet/cabinet_YC-5.png"
    },
    {
      "id": "YC-6",
      "model": "D2-60双色门",
      "name": "D2-60双色门",
      "spec": "",
      "type": "浴室柜",
      "price": 800
    },
    {
      "id": "YC-7",
      "model": "D6-60",
      "name": "D6-60",
      "spec": "",
      "type": "浴室柜",
      "price": 800,
      "image": "images/cabinet/cabinet_YC-7.png"
    },
    {
      "id": "YC-8",
      "model": "4335支架（黑.白）4335B/W",
      "name": "4335支架（黑.白）4335B/W",
      "spec": "",
      "type": "支架",
      "price": 350,
      "image": "images/cabinet/cabinet_YC-8.png"
    },
    {
      "id": "YC-9",
      "model": "43-白浪",
      "name": "43-白浪",
      "spec": "",
      "type": "浴室柜",
      "price": 480,
      "image": "images/cabinet/cabinet_YC-9.png"
    },
    {
      "id": "YC-10",
      "model": "D60-SK天空蓝",
      "name": "D60-SK天空蓝",
      "spec": "",
      "type": "浴室柜",
      "price": 800,
      "image": "images/cabinet/cabinet_YC-10.png"
    },
    {
      "id": "YC-11",
      "model": "43-豆沙绿",
      "name": "43-豆沙绿",
      "spec": "",
      "type": "浴室柜",
      "price": 480
    },
    {
      "id": "YC-12",
      "model": "D3-60圆镜",
      "name": "D3-60圆镜",
      "spec": "特价引流款",
      "type": "浴室柜",
      "price": 750,
      "image": "images/cabinet/cabinet_YC-12.png"
    },
    {
      "id": "YC-13",
      "model": "43-水泥灰",
      "name": "43-水泥灰",
      "spec": "",
      "type": "浴室柜",
      "price": 480,
      "image": "images/cabinet/cabinet_YC-13.jpeg"
    }
  ]
};
